[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
# This tells the compiler to use the memory map (link.x) and defmt logs (defmt.x)
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32L476RG"