//Notes:
//  in property= Read Only property
//  out property= Write Only property
//  in-out property= Read Write property 
//  callback= model a function to update GUI from a Rust logic program     
//  pure callback= model a function to update compute and return a value. Should not modify the GUI state      

import { AboutSlint, VerticalBox } from "std-widgets.slint";

struct PlotPoint {
    x: float,
    y: float,
    z: float,
}

export component ControllerWindow inherits Window {

    //Properties of the GUI
    in-out property <string> connection_msg: "Not Connected";
    in property <image> cam1_display;
    in property <image> cam2_display;
    in property <image> lidar_measurement;
    //Callbacks to interact with the GUI
    callback update_cams();
    callback plot_data(data: [PlotPoint], chart_type: string);

    width: 1000px;
    always-on-top: false;
    height: 800px;
    title: "Controller";


    HorizontalLayout {
        VerticalLayout {
            width: parent.width * 2 / 3.0;
            HorizontalLayout {
                cam1_display := Image {
                    source: root.cam1_display;
                    horizontal-alignment: left;
                    vertical-alignment: top;
                }
                cam2_display := Image {
                    source: root.cam2_display;
                    horizontal-alignment: left;
                    vertical-alignment: top;
                }
            }
            lidar_measurement := Image {
                source: root.lidar_measurement;
                horizontal-alignment: left;
                vertical-alignment: top;
            }
        }
        VerticalLayout {
            Text {
            text: "Hello World!";
        }
        AboutSlint {
            preferred-height: 150px;
        }
        }
        
    }
}
